#!/bin/sh
# archive-integrity COMMAND ...
# poslib's archive command line, with the image's packages. The protocol
# is docs/archive-integrity.txt. Signing in prints the address to open,
# since there is no browser here.
case ${1:-} in
    -h|--help) set -- help ;;
esac
exec emacs -Q --batch \
    -l /usr/local/share/clankos/lisp/clankos-packages.el \
    -l pos-seal -l pos-signin \
    --eval '(setq pos-signin-browse-function
                  (lambda (url)
                    (message "Open this address in a browser to sign in:\n%s" url)))' \
    -f pos-seal-batch "$@"
